/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.CRM;

import com.formdev.flatlaf.FlatIntelliJLaf;
import java.sql.ResultSet;
import java.util.Vector;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.MySQL;

/**
 *
 * @author Kavithma
 */
public class GuestTable extends javax.swing.JDialog {

    private Loyaltyt loyaltyPanel;
    private ComplaintTracker complaintPanel;
    private NotificationCenter notificationPanel;

    public GuestTable(JFrame parentFrame, boolean modal, Object callerPanel) {
        super(parentFrame, modal);

        if (callerPanel == null) {
            throw new IllegalArgumentException("Caller panel cannot be null");
        }

        // Identify and assign the appropriate panel
        if (callerPanel instanceof Loyaltyt) {
            this.loyaltyPanel = (Loyaltyt) callerPanel;
        } else if (callerPanel instanceof ComplaintTracker) {
            this.complaintPanel = (ComplaintTracker) callerPanel;
        } else if (callerPanel instanceof NotificationCenter) {
            this.notificationPanel = (NotificationCenter) callerPanel;
        } else {
            throw new IllegalArgumentException("Unsupported panel type");
        }

        initComponents();
        loadGuests();
    }

    private void loadGuests() {
        try {
            ResultSet resultSet = MySQL.executeSearch(
                    "SELECT g.reg_date, g.guest_id, g.firstName, g.lastName, g.email, "
                    + "rs.name AS status_name, g.mobile, c.name AS country_name "
                    + "FROM guests g "
                    + "INNER JOIN resident_status rs ON g.status = rs.id "
                    + "INNER JOIN country c ON g.country = c.id"
            );

            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.setRowCount(0);

            while (resultSet.next()) {
                Vector<String> vector = new Vector<>();
                vector.add(resultSet.getString("reg_date"));         // 0 - Registered Date
                vector.add(resultSet.getString("guest_id"));         // 1 - Guest ID
                vector.add(resultSet.getString("firstName"));        // 2 - First Name
                vector.add(resultSet.getString("lastName"));         // 3 - Last Name
                vector.add(resultSet.getString("email"));            // 4 - Email
                vector.add(resultSet.getString("status_name"));      // 5 - Status (Name, not ID)
                vector.add(resultSet.getString("mobile"));           // 6 - Mobile
                vector.add(resultSet.getString("country_name"));     // 7 - Country (Name, not ID)

                model.addRow(vector);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error loading guest data: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new com.k33ptoo.components.KGradientPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        kGradientPanel1.setkEndColor(new java.awt.Color(255, 255, 255));
        kGradientPanel1.setkStartColor(new java.awt.Color(91, 91, 37));

        jTable1.setBackground(new java.awt.Color(231, 228, 228));
        jTable1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 153, 153), new java.awt.Color(204, 204, 204), null, null));
        jTable1.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Date", "Guest ID", "First Name", "Last Name", "Email", "Resident status", "Contact", "Country"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setGridColor(new java.awt.Color(204, 204, 204));
        jTable1.setRowHeight(28);
        jTable1.setSelectionBackground(new java.awt.Color(153, 153, 153));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap(118, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 760, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(117, 117, 117))
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap(59, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 676, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked

        int selectedRow = jTable1.getSelectedRow();
        if (selectedRow != -1 && evt.getClickCount() == 2) {
            String selectedValue = String.valueOf(jTable1.getValueAt(selectedRow, 1));
            String selectedValue2 = String.valueOf(jTable1.getValueAt(selectedRow, 4));

            if (loyaltyPanel != null && loyaltyPanel.getjTextField4() != null) {

                loyaltyPanel.getjTextField4().setText(selectedValue);
                this.dispose();
            } else if (complaintPanel != null && complaintPanel.getjTextField6() != null) {

                complaintPanel.getjTextField6().setText(selectedValue);
                this.dispose();
            } else if (notificationPanel != null && notificationPanel.getjTextField4() != null) {

                notificationPanel.getjTextField4().setText(selectedValue2);
                this.dispose();
            } else {
                System.out.println("No valid panel or text field is available!");
            }
        }


    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private com.k33ptoo.components.KGradientPanel kGradientPanel1;
    // End of variables declaration//GEN-END:variables
}
