/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.CRM;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.util.Vector;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;
import model.MySQL;

/**
 *
 * @author Kavithma
 */
public class Loyaltyt extends javax.swing.JPanel {

    /**
     * Creates new form Guests
     */
    public Loyaltyt() {
        initComponents();
        loadComboBoxes();
        setNewLoyaltyId();
        loadLoyaltyData(null);

        jTextField2.setEditable(false);
        jTextField4.setEditable(false);
        jTextField3.grabFocus();
    }

    public JTextField getjTextField4() {
        return jTextField4;
    }

    private void setNewLoyaltyId() {
        try {

            ResultSet rs = MySQL.executeSearch("SELECT MAX(loyalty_id) AS max_id FROM loyalty");
            String newLoyaltyId = "LOY-000001";

            if (rs.next()) {
                String maxId = rs.getString("max_id");
                if (maxId != null) {

                    int numericPart = Integer.parseInt(maxId.split("-")[1]);
                    numericPart++;
                    newLoyaltyId = String.format("LOY-%06d", numericPart);
                }
            }

            jTextField2.setText(newLoyaltyId);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error setting loyalty ID: " + e.getMessage());
        }
    }

    private void loadLoyaltyData(String orderBy) {
        try {
            String query = "SELECT l.loyalty_id, l.guest_id, l.points, m.level AS membership_level "
                    + "FROM loyalty l "
                    + "INNER JOIN membership m ON l.membership_id = m.id";

            if (orderBy != null) {
                switch (orderBy) {
                    case "Oldest":
                        query += " ORDER BY l.loyalty_id ASC";
                        break;
                    case "Latest":
                        query += " ORDER BY l.loyalty_id DESC";
                        break;
                    case "Most Points":
                        query += " ORDER BY l.points DESC";
                        break;
                }
            }

            javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) jTable1.getModel();
            model.setRowCount(0);

            ResultSet rs = MySQL.executeSearch(query);

            while (rs.next()) {
                Vector vector = new Vector();
                vector.add(rs.getString("guest_id"));
                vector.add(rs.getString("loyalty_id"));
                vector.add(rs.getString("points"));
                vector.add(rs.getString("membership_level"));

                model.addRow(vector);

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error loading loyalty data: " + e.getMessage());
        }
    }

    private void reset() {
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
        jComboBox2.setSelectedIndex(0);

        jTextField3.setEnabled(true);
        jTable1.clearSelection();

    }

    private void loadComboBoxes() {
        try {

            ResultSet membershipRs = MySQL.executeSearch("SELECT id, level FROM membership");
            jComboBox2.removeAllItems();
            while (membershipRs.next()) {
                String id = membershipRs.getString("id");
                String type = membershipRs.getString("level");
                jComboBox2.addItem(id + " - " + type);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error loading combo box data: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new com.k33ptoo.components.KGradientPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        kButton1 = new com.k33ptoo.components.KButton();
        kButton2 = new com.k33ptoo.components.KButton();
        kButton3 = new com.k33ptoo.components.KButton();
        jComboBox2 = new javax.swing.JComboBox<>();
        jTextField4 = new javax.swing.JTextField();
        kButton4 = new com.k33ptoo.components.KButton();
        jLabel5 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(204, 204, 204));
        setPreferredSize(new java.awt.Dimension(1640, 965));

        kGradientPanel1.setkEndColor(new java.awt.Color(255, 255, 255));
        kGradientPanel1.setkGradientFocus(1000);
        kGradientPanel1.setkStartColor(new java.awt.Color(91, 91, 37));

        jTable1.setBackground(new java.awt.Color(231, 228, 228));
        jTable1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 153, 153), new java.awt.Color(204, 204, 204), null, null));
        jTable1.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Guest ID", "Loyalty ID", "Points", "Membership"
            }
        ));
        jTable1.setGridColor(new java.awt.Color(204, 204, 204));
        jTable1.setRowHeight(28);
        jTable1.setSelectionBackground(new java.awt.Color(153, 153, 153));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel1.setText("Filter By: ");

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel2.setText("Points");

        jTextField2.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel3.setText("Loyalty Id");

        jTextField3.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel4.setText("Membership Level");

        kButton1.setText("Register");
        kButton1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        kButton1.setkBackGroundColor(new java.awt.Color(153, 153, 153));
        kButton1.setkEndColor(new java.awt.Color(51, 102, 0));
        kButton1.setkHoverEndColor(new java.awt.Color(153, 153, 153));
        kButton1.setkHoverForeGround(new java.awt.Color(102, 102, 102));
        kButton1.setkHoverStartColor(new java.awt.Color(102, 102, 102));
        kButton1.setkSelectedColor(new java.awt.Color(102, 102, 102));
        kButton1.setkStartColor(new java.awt.Color(102, 102, 102));
        kButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton1ActionPerformed(evt);
            }
        });

        kButton2.setText("Update");
        kButton2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        kButton2.setkBackGroundColor(new java.awt.Color(102, 102, 102));
        kButton2.setkHoverForeGround(new java.awt.Color(102, 102, 102));
        kButton2.setkHoverStartColor(new java.awt.Color(204, 204, 204));
        kButton2.setkStartColor(new java.awt.Color(102, 102, 102));
        kButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton2ActionPerformed(evt);
            }
        });

        kButton3.setText("Select");
        kButton3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        kButton3.setkBackGroundColor(new java.awt.Color(102, 102, 102));
        kButton3.setkEndColor(new java.awt.Color(102, 102, 0));
        kButton3.setkHoverForeGround(new java.awt.Color(102, 102, 102));
        kButton3.setkHoverStartColor(new java.awt.Color(102, 102, 102));
        kButton3.setkSelectedColor(new java.awt.Color(102, 102, 102));
        kButton3.setkStartColor(new java.awt.Color(153, 153, 153));
        kButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton3ActionPerformed(evt);
            }
        });

        jComboBox2.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jTextField4.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N

        kButton4.setText("Delete");
        kButton4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        kButton4.setkBackGroundColor(new java.awt.Color(102, 102, 102));
        kButton4.setkEndColor(new java.awt.Color(102, 102, 0));
        kButton4.setkHoverForeGround(new java.awt.Color(102, 102, 102));
        kButton4.setkHoverStartColor(new java.awt.Color(102, 102, 102));
        kButton4.setkSelectedColor(new java.awt.Color(102, 102, 102));
        kButton4.setkStartColor(new java.awt.Color(153, 153, 153));
        kButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton4ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel5.setText("Guest Id");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Filter", "Oldest", "Latest", "Most Points" }));
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 684, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, kGradientPanel1Layout.createSequentialGroup()
                                        .addComponent(kButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(kButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(kButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jComboBox2, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel2)))
                                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                                        .addComponent(kButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(40, 40, 40))))
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(425, Short.MAX_VALUE))
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(kButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(110, 110, 110)
                        .addComponent(kButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(kButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(kButton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1))
                .addContainerGap(247, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(kGradientPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void kButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton3ActionPerformed
        JFrame parentFrame = (JFrame) SwingUtilities.getWindowAncestor(this);
        Loyaltyt loyaltyPanel = this;

        GuestTable gt = new GuestTable(parentFrame, true, loyaltyPanel);
        gt.setVisible(true);
    }//GEN-LAST:event_kButton3ActionPerformed

    private void kButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton4ActionPerformed

        int selectedRow = jTable1.getSelectedRow();

        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select a record to delete.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String loyaltyId = jTextField2.getText().trim();

        int confirm = JOptionPane.showConfirmDialog(this, "Are you sure you want to delete this loyalty entry?", "Confirm Deletion", JOptionPane.YES_NO_OPTION);
        if (confirm != JOptionPane.YES_OPTION) {
            return;
        }

        try {
            String query = "DELETE FROM loyalty WHERE loyalty_id = '" + loyaltyId + "'";
            MySQL.executeIUD(query);
            JOptionPane.showMessageDialog(this, "Loyalty record deleted successfully!");

            reset();
            setNewLoyaltyId();
            loadLoyaltyData(null);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error deleting record: " + e.getMessage());
        }
    }//GEN-LAST:event_kButton4ActionPerformed

    private void kButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton1ActionPerformed

        String loyaltyId = jTextField2.getText().trim();
        String guestId = jTextField4.getText().trim();
        int points;

        if (guestId.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Guest ID cannot be empty.");
            return;
        }

        try {
            points = Integer.parseInt(jTextField3.getText().trim());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Invalid points input. Please enter a valid number.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (points < 0) {
            JOptionPane.showMessageDialog(this, "Points cannot be negative.");
            return;
        }

        String membershipIdWithLevel = jComboBox2.getSelectedItem().toString();
        String[] parts = membershipIdWithLevel.split(" - ");
        String membershipId = parts[0];

        if (membershipId.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Membership ID cannot be empty.");
            return;
        }

        try {
            ResultSet rs = MySQL.executeSearch("SELECT * FROM loyalty WHERE guest_id = '" + guestId + "'");
            if (rs.next()) {
                JOptionPane.showMessageDialog(this, "This guest already has a loyalty record.", "Warning", JOptionPane.WARNING_MESSAGE);
                return;
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error checking guest ID: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            String query = String.format(
                    "INSERT INTO loyalty (loyalty_id, points, guest_id, membership_id) VALUES ('%s', %d, '%s', '%s')",
                    loyaltyId, points, guestId, membershipId);

            MySQL.executeIUD(query);
            JOptionPane.showMessageDialog(this, "Guest registered successfully!");

            reset();
            setNewLoyaltyId();
            loadLoyaltyData(null);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error registering guest: " + e.getMessage());
        }


    }//GEN-LAST:event_kButton1ActionPerformed

    private void kButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton2ActionPerformed

        int selectedRow = jTable1.getSelectedRow();

        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select a record to update.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String loyaltyId = jTextField2.getText().trim();
        String membershipIdWithLevel = jComboBox2.getSelectedItem().toString();
        String[] parts = membershipIdWithLevel.split(" - ");
        String membershipId = parts[0];

        int newPoints;
        try {
            newPoints = Integer.parseInt(jTextField3.getText().trim());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Invalid points input.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (newPoints < 0) {
            JOptionPane.showMessageDialog(this, "Points cannot be negative.");
            return;
        }

        try {
            String query = String.format(
                    "UPDATE loyalty SET points = %d, membership_id = '%s' WHERE loyalty_id = '%s'",
                    newPoints, membershipId, loyaltyId);

            MySQL.executeIUD(query);
            JOptionPane.showMessageDialog(this, "Loyalty record updated successfully!");

            reset();
            setNewLoyaltyId();
            loadLoyaltyData(null);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error updating record: " + e.getMessage());
        }
    }//GEN-LAST:event_kButton2ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        kButton1.setEnabled(false);
        kButton3.setEnabled(false);
        int row = jTable1.getSelectedRow();

        String gid = String.valueOf(jTable1.getValueAt(row, 0));
        jTextField4.setText(gid);

        String lid = String.valueOf(jTable1.getValueAt(row, 1));
        jTextField2.setText(lid);

        String points = String.valueOf(jTable1.getValueAt(row, 2));
        jTextField3.setText(points);

        String comboValue = String.valueOf(jTable1.getValueAt(row, 3)).trim();

        for (int i = 0; i < jComboBox2.getItemCount(); i++) {
            String item = jComboBox2.getItemAt(i).toString();
            String itemLevel = item.split(" - ")[1].trim(); // get the level part

            if (itemLevel.equalsIgnoreCase(comboValue)) {
                jComboBox2.setSelectedItem(item);
                break;
            }
        }


    }//GEN-LAST:event_jTable1MouseClicked

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        if (evt.getStateChange() == java.awt.event.ItemEvent.SELECTED) {
            String selectedFilter = jComboBox1.getSelectedItem().toString();
            loadLoyaltyData(selectedFilter);
        }
    }//GEN-LAST:event_jComboBox1ItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private com.k33ptoo.components.KButton kButton1;
    private com.k33ptoo.components.KButton kButton2;
    private com.k33ptoo.components.KButton kButton3;
    private com.k33ptoo.components.KButton kButton4;
    private com.k33ptoo.components.KGradientPanel kGradientPanel1;
    // End of variables declaration//GEN-END:variables
}
