package Admin;

import gui.ReservationAndBooking.*;
import java.sql.ResultSet;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.MySQL;

/**
 *
 * @author Sudham
 */
public class AdminGuestRegistration extends javax.swing.JPanel {

    public AdminGuestRegistration() {
        initComponents();
        loadNextGuestID();
        loadGuests();
        loadComboBoxes1();
        loadComboBoxes2();
    }

    private void loadNextGuestID() {
        jLabel25.setText(returnNextGuestId());

    }

    private String extractSelectedId(javax.swing.JComboBox<String> comboBox) {
        String selectedItem = comboBox.getSelectedItem().toString();
        return selectedItem.split(" - ")[0]; // Extracts the ID before the dash
    }

    private void reset() {
        jTextField6.setText("");
        jTextField7.setText("");
        jTextField11.setText("");
        jTextField12.setText("");
        jTextField11.setEditable(true);
        jTextField6.grabFocus();
        jComboBox3.setSelectedIndex(0);
        jComboBox4.setSelectedIndex(0);

        jTable1.clearSelection();
        search();
        loadNextGuestID();
    }

    private void search() {
        int sort = jComboBox3.getSelectedIndex();

//        if (sort == 0) {
//            loadGuests("first_name", "ASC", jTextField1.getText());
//        } else if (sort == 1) {
//            loadGuests("first_name", "DESC", jTextField1.getText());
//        }
    }

    private void loadGuests() {
        try {
            ResultSet resultSet = MySQL.executeSearch(
                    "SELECT g.guest_id, g.firstName, g.lastName, g.mobile, g.email, rs.name AS status_name, c.name AS country_name, g.reg_date "
                    + "FROM guests g "
                    + "INNER JOIN resident_status rs ON g.status = rs.id "
                    + "INNER JOIN country c ON g.country = c.id"
            );

            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.setRowCount(0);

            while (resultSet.next()) {
                Vector<String> vector = new Vector<>();
                vector.add(resultSet.getString("guest_id"));
                vector.add(resultSet.getString("firstName"));
                vector.add(resultSet.getString("lastName"));
                vector.add(resultSet.getString("mobile"));
                vector.add(resultSet.getString("email"));
                vector.add(resultSet.getString("status_name"));
                vector.add(resultSet.getString("country_name"));
                vector.add(resultSet.getString("reg_date"));

                model.addRow(vector);
            }

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error loading guest data: " + e.getMessage());
        }
    }

    private void loadComboBoxes1() {
        try {

            ResultSet membershipRs = MySQL.executeSearch("SELECT id, name FROM resident_status");
            jComboBox3.removeAllItems();
            while (membershipRs.next()) {
                String id = membershipRs.getString("id");
                String rname = membershipRs.getString("name");
                jComboBox3.addItem(id + " - " + rname);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error loading combo box data: " + e.getMessage());
        }
    }

    private void loadComboBoxes2() {
        try {

            ResultSet membershipRs = MySQL.executeSearch("SELECT id, name FROM country");
            jComboBox4.removeAllItems();
            while (membershipRs.next()) {
                String id = membershipRs.getString("id");
                String cname = membershipRs.getString("name");
                jComboBox4.addItem(id + " - " + cname);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error loading combo box data: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new com.k33ptoo.components.KGradientPanel();
        jLabel8 = new javax.swing.JLabel();
        kButton2 = new com.k33ptoo.components.KButton();
        kButton4 = new com.k33ptoo.components.KButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        kButton3 = new com.k33ptoo.components.KButton();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(204, 204, 204));
        setPreferredSize(new java.awt.Dimension(1640, 965));

        kGradientPanel1.setkEndColor(new java.awt.Color(255, 255, 255));
        kGradientPanel1.setkGradientFocus(1000);
        kGradientPanel1.setkStartColor(new java.awt.Color(91, 91, 37));
        kGradientPanel1.setPreferredSize(new java.awt.Dimension(600, 909));

        jLabel8.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        jLabel8.setText("Guest Registration");

        kButton2.setText("Update");
        kButton2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        kButton2.setkBackGroundColor(new java.awt.Color(102, 102, 102));
        kButton2.setkHoverForeGround(new java.awt.Color(102, 102, 102));
        kButton2.setkHoverStartColor(new java.awt.Color(204, 204, 204));
        kButton2.setkStartColor(new java.awt.Color(102, 102, 102));
        kButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton2ActionPerformed(evt);
            }
        });

        kButton4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        kButton4.setText("Clear All");
        kButton4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        kButton4.setkBackGroundColor(new java.awt.Color(102, 102, 102));
        kButton4.setkEndColor(new java.awt.Color(102, 102, 0));
        kButton4.setkHoverForeGround(new java.awt.Color(102, 102, 102));
        kButton4.setkHoverStartColor(new java.awt.Color(102, 102, 102));
        kButton4.setkSelectedColor(new java.awt.Color(102, 102, 102));
        kButton4.setkStartColor(new java.awt.Color(153, 153, 153));
        kButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton4ActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel14.setText("Guest ID :");

        jLabel22.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel22.setText("Country :");

        jLabel9.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel9.setText("Last Name :");

        jLabel10.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel10.setText("Email :");

        jLabel11.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel11.setText("Mobile :");

        jTextField6.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N

        jTextField7.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N

        jTextField11.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N

        jTextField12.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N

        jLabel25.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N

        jTable1.setBackground(new java.awt.Color(231, 228, 228));
        jTable1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 153, 153), new java.awt.Color(204, 204, 204), null, null));
        jTable1.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Guest ID", "First Name", "Last Name", "Mobile", "Email", "Status", "Country", "Registered Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setGridColor(new java.awt.Color(204, 204, 204));
        jTable1.setRowHeight(28);
        jTable1.setSelectionBackground(new java.awt.Color(153, 153, 153));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        kButton3.setText("Register");
        kButton3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        kButton3.setkBackGroundColor(new java.awt.Color(102, 102, 102));
        kButton3.setkHoverForeGround(new java.awt.Color(102, 102, 102));
        kButton3.setkHoverStartColor(new java.awt.Color(204, 204, 204));
        kButton3.setkStartColor(new java.awt.Color(102, 102, 102));
        kButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton3ActionPerformed(evt);
            }
        });

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select" }));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel23.setText("First Name :");

        jLabel24.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel24.setText("Status :");

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select" }));
        jComboBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, kGradientPanel1Layout.createSequentialGroup()
                                    .addComponent(kButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(kButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(47, 47, 47)
                                    .addComponent(kButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                    .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                            .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jTextField7)
                                                .addComponent(jTextField11)
                                                .addComponent(jTextField12)
                                                .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(265, 265, 265)
                                    .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(698, 698, 698)))
                            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1052, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(162, 162, 162)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 1104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(kGradientPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(524, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(kGradientPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 698, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(261, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void kButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton4ActionPerformed
        reset();
        loadNextGuestID();
    }//GEN-LAST:event_kButton4ActionPerformed

    private void kButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton2ActionPerformed
        String fName = jTextField6.getText();
        String lName = jTextField7.getText();
        String email = jTextField12.getText();
        String mobile = jTextField11.getText();

        if (fName.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter your First Name", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        } else if (lName.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter your Last Name", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        } else if (mobile.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter your Mobile", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        } else if (!mobile.matches("^07[01245678]{1}[0-9]{7}$")) {
            JOptionPane.showMessageDialog(this, "Invalid Mobile Number", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        } else if (email.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter your email", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        } else if (!email.matches("^(?=.{1,64}@)[A-Za-z0-9\\+_-]+(\\.[A-Za-z0-9\\+_-]+)*@[^-][A-Za-z0-9\\+-]+(\\.[A-Za-z0-9\\+-]+)*(\\.[A-Za-z]{2,})$")) {
            JOptionPane.showMessageDialog(this, "Please enter a valid email address", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String statusId = extractSelectedId(jComboBox3);
        String countryId = extractSelectedId(jComboBox4);

        try {
            ResultSet resultSet = MySQL.executeSearch("SELECT * FROM `guests` WHERE `mobile` = '" + mobile + "'");
            if (resultSet.next()) {
                MySQL.executeIUD("UPDATE `guests` SET `firstName` = '" + fName + "', `lastName` = '" + lName + "', `email` = '" + email + "', "
                        + "`status` = '" + statusId + "', `country` = '" + countryId + "' WHERE `mobile` = '" + mobile + "'");

                loadGuests();
                reset();
                JOptionPane.showMessageDialog(this, "Guest updated successfully!", "Information", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Guest not found for update!", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error updating guest!", "Error", JOptionPane.ERROR_MESSAGE);
        }

    }

    private String returnNextGuestId() {
        try {
            // Execute an SQL query to fetch the last guest ID from the `guests` table.
            // The query orders the results by `guest_id` in descending order and limits to 1 row.
            ResultSet rs = MySQL.executeSearch("SELECT `guest_id` FROM `guests` ORDER BY guest_id DESC LIMIT 1");

            // Check if the query returned a result (i.e., there is at least one record in the table).
            if (rs.next()) {
                // Retrieve the last guest ID from the result set as a string.
                String lastId = rs.getString("guest_id");

                // Define the prefix for the new ID (e.g., "GUS-").
                String prefix = "GUS-";

                // Extract the numeric part of the ID by splitting the string at the hyphen ("-")
                // and parsing the second part as an integer.
                int id = Integer.parseInt(lastId.split("-")[1]);

                // Increment the numeric part of the ID to generate the next ID.
                id++;

                // Format the new ID by appending the incremented number, padded with leading zeros to ensure 5 digits.
                String newId = prefix + String.format("%06d", id);
                return newId;
            }
            // Set the generated new ID as the text in the `jTextField1` UI component.
            //jTextField1.setText(newId);
//        } 

        } catch (Exception e) {
            // Handle any exceptions that may occur during the execution of the SQL query or ID generation.
            // Print the stack trace of the exception for debugging purposes.
            e.printStackTrace();

            // Display an error message to the user in a dialog box if an error occurs.
            JOptionPane.showMessageDialog(this, "Error generating new guest ID", "Error", JOptionPane.ERROR_MESSAGE);
        }
        return null;


    }//GEN-LAST:event_kButton2ActionPerformed

    private void kButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton3ActionPerformed
        // GuestDetails
        String fName = jTextField6.getText();
        String lName = jTextField7.getText();
        String email = jTextField12.getText();
        String mobile = jTextField11.getText();

        if (fName.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter your First Name", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        } else if (lName.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter your Last Name", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        } else if (mobile.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter your Mobile", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        } else if (!mobile.matches("^07[01245678]{1}[0-9]{7}$")) {
            JOptionPane.showMessageDialog(this, "Invalid Mobile Number", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        } else if (email.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter your email", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        } else if (!email.matches("^(?=.{1,64}@)[A-Za-z0-9\\+_-]+(\\.[A-Za-z0-9\\+_-]+)*@[^-][A-Za-z0-9\\+-]+(\\.[A-Za-z0-9\\+-]+)*(\\.[A-Za-z]{2,})$")) {
            JOptionPane.showMessageDialog(this, "Please enter a valid email address", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String statusId = extractSelectedId(jComboBox3);
        String countryId = extractSelectedId(jComboBox4);

        try {
            ResultSet resultSet = MySQL.executeSearch("SELECT * FROM `guests` WHERE `mobile` = '" + mobile + "' AND `email` = '" + email + "'");
            if (resultSet.next()) {
                JOptionPane.showMessageDialog(this, "Guest already registered!", "Warning", JOptionPane.WARNING_MESSAGE);
            } else {
                String guestId = returnNextGuestId();
                String regDate = new SimpleDateFormat("yyyy-MM-dd").format(new Date());

                MySQL.executeIUD("INSERT INTO `guests` (`guest_id`, `firstName`, `lastName`, `mobile`, `email`, `status`, `country`, `reg_date`) "
                        + "VALUES ('" + guestId + "', '" + fName + "', '" + lName + "', '" + mobile + "', '" + email + "', '" + statusId + "', '" + countryId + "', '" + regDate + "')");

                JOptionPane.showMessageDialog(this, "Guest registered successfully!", "Information", JOptionPane.INFORMATION_MESSAGE);
                loadGuests();
                reset();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Guest registration failed!", "Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }//GEN-LAST:event_kButton3ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // setGuestName();
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int row = jTable1.getSelectedRow();

        String guestId = String.valueOf(jTable1.getValueAt(row, 0));
        String fname = String.valueOf(jTable1.getValueAt(row, 1));
        String lname = String.valueOf(jTable1.getValueAt(row, 2));
        String mobile = String.valueOf(jTable1.getValueAt(row, 3));
        String email = String.valueOf(jTable1.getValueAt(row, 4));
        String statusName = String.valueOf(jTable1.getValueAt(row, 5));
        String countryName = String.valueOf(jTable1.getValueAt(row, 6));

        jLabel25.setText(guestId);
        jTextField6.setText(fname);
        jTextField7.setText(lname);
        jTextField11.setText(mobile);
        jTextField11.setEditable(false);
        jTextField12.setText(email);

        // Set comboBox3 (resident status) by matching name
        for (int i = 0; i < jComboBox3.getItemCount(); i++) {
            String item = jComboBox3.getItemAt(i);
            if (item.endsWith(" - " + statusName)) {
                jComboBox3.setSelectedIndex(i);
                break;
            }
        }

        // Set comboBox4 (country) by matching name
        for (int i = 0; i < jComboBox4.getItemCount(); i++) {
            String item = jComboBox4.getItemAt(i);
            if (item.endsWith(" - " + countryName)) {
                jComboBox4.setSelectedIndex(i);
                break;
            }
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jComboBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private com.k33ptoo.components.KButton kButton2;
    private com.k33ptoo.components.KButton kButton3;
    private com.k33ptoo.components.KButton kButton4;
    private com.k33ptoo.components.KGradientPanel kGradientPanel1;
    // End of variables declaration//GEN-END:variables
}
